services:
  api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"         # host:container (le container écoute 8000 via gunicorn)
    volumes:
      - .:/app              # pratique pour debug; tu peux l’enlever en prod stricte
      - ./staticfiles:/app/staticfiles
      - ./db.sqlite3:/app/db.sqlite3   # si tu restes sur SQLite
    restart: unless-stopped
    depends_on: []
    # Uncomment if you enable Postgres
    # depends_on:
    #   - db

  # db:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   pgdata:
