name: CI + Deploy (main)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ci-deploy-main
  cancel-in-progress: true

jobs:
  test:
    name: Build & Test (Docker)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker build -t weebbackend:${{ github.sha }} .

      - name: Run Django tests inside container
        env:
          DJANGO_SECRET_KEY: "ci-secret"
          DJANGO_DEBUG: "0"
        run: |
          docker run --rm \
            -e DJANGO_SECRET_KEY \
            -e DJANGO_DEBUG \
            weebbackend:${{ github.sha }} \
            python manage.py test --noinput -v 2

  deploy:
    name: Deploy to RPi (only on main)
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && success() }}

    steps:
      - name: Remote deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          script_stop: true
          ssh_config: |
            Host *
              StrictHostKeyChecking no
          script: |
            bash /home/rpiserver/weeb-website-django/deploy.sh
